POST http://localhost:5000/
Content-Type: application/json

{
  "type": "user_fraud",
  "uid": "C1420196421"
}

###
POST http://localhost:5000/
Content-Type: application/json

{
  "type": "user_top",
  "uid": "C1420196421"
}

###
POST http://localhost:5000/
Content-Type: application/json

{
  "type": "user_incoming",
  "uid": "C553264065",
  "start_date": "2000-01-01",
  "end_date": "2022-06-09"
}
